#!/bin/bash

if [ $(id -u) = '0' ]; then
	echo "should not run as superuser!"
	exit 1
fi

if [ "$#" -ge '1' ]; then
	arg=$1
else
	arg="start"
fi	

if [ "$arg" != 'start' -a "$arg" != 'restart' -a "$arg" != 'stop' ]; then
	echo "unexpected command"
	exit 1
fi

if [ "$arg" = 'start' ]; then
	if [ "$(pidof ccnud)" ]; then
		echo " * ccnud already running"
	else
		echo " * Starting ccnud"
		if [ "$#" -ge '2' ]; then
			result=`~/projects/cs219_bfr/bin/ccnud $2`
			echo $result
		else
			result=`~/projects/cs219_bfr/bin/ccnud`
		fi
	fi

	sleep 0.5

	if [ "$(pidof bfrd)" ]; then
		echo " * bfrd already running"
	else
		echo " * Starting bfrd"
		if [ "$#" -ge '3' ]; then
			result=`~/projects/cs219_bfr/bin/bfrd $3`
		else
			result=`~/projects/cs219_bfr/bin/bfrd`
		fi
	fi

elif [ "$arg" = 'restart' ]; then
	if [ "$(pidof ccnud)" ]; then
		echo " * Shutting down ccnud"
		killall ccnud
	fi

	echo " * Starting ccnud"
	if [ "$#" -ge '2' ]; then
		result=`~/projects/cs219_bfr/bin/ccnud $2`
		echo $result
	else
		result=`~/projects/cs219_bfr/bin/ccnud`
	fi

	if [ "$(pidof bfrd)" ]; then
		echo " * Shutting down bfrd"
		killall bfrd
	fi

	sleep 1
	echo " * Starting bfrd"

	if [ "$#" -ge '3' ]; then
		result=`~/projects/cs219_bfr/bin/bfrd $3`
	else
		result=`~/projects/cs219_bfr/bin/bfrd`
	fi

elif [ "$arg" = 'stop' ]; then
	echo " * Shutting down ccnud"
	killall ccnud
	echo " * Shutting down bfrd"
	killall bfrd
fi
