#!/bin/bash

MY_PATH=$(readlink -m $0)
MY_PATH=${MY_PATH/%bfr_ctl/}

start() {
	if [ "$(pidof ccnud)" ]; then
		echo " * ccnud already running"
	else
		echo " * Starting ccnud"
		if [ "$#" -ge '2' ]; then
			result=`$MY_PATH/../bin/ccnud $2`
			echo $result
		else
			result=`$MY_PATH/../bin/ccnud`
		fi
	fi

	sleep 0.5

	if [ "$(pidof bfrd)" ]; then
		echo " * bfrd already running"
	else
		echo " * Starting bfrd"
		if [ "$#" -ge '3' ]; then
			result=`$MY_PATH/../bin/bfrd $3`
		else
			result=`$MY_PATH/../bin/bfrd`
		fi
	fi
}

restart() {
	if [ "$(pidof ccnud)" ]; then
		echo " * Shutting down ccnud"
		killall ccnud
	fi

	echo " * Starting ccnud"
	if [ "$#" -ge '2' ]; then
		result=`$MY_PATH/../bin/ccnud $2`
		echo $result
	else
		result=`$MY_PATH/../bin/ccnud`
	fi

	if [ "$(pidof bfrd)" ]; then
		echo " * Shutting down bfrd"
		killall bfrd
	fi

	sleep 1
	echo " * Starting bfrd"

	if [ "$#" -ge '3' ]; then
		result=`$MY_PATH/../bin/bfrd $3`
	else
		result=`$MY_PATH/../bin/bfrd`
	fi
}

stop() {
	echo " * Shutting down ccnud"
	killall ccnud
	echo " * Shutting down bfrd"
	killall bfrd
}

loc() {
	$MY_PATH/../apps/bin/cloc $1 $2
}

if [ $(id -u) = '0' ]; then
	echo " * Should not run as superuser!"
	exit 1
fi

if [ "$#" -ge '1' ]; then
	arg=$1
else
	arg="start"
fi	

case "$arg" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	loc)
		loc $2 $3
		;;
	*)
		echo " * Usage: $0 {start|stop|restart|loc}"
		exit 1
esac

exit 0
