#!/bin/bash

if [ $(id -u) = '0' ]; then
	echo "should not run as superuser!"
	exit 1
fi

if [ "$#" -ge '1' ]; then
	arg=$1
else
	arg="start"
fi	

if [ "$arg" != 'start' -a "$arg" != 'stop' ]; then
	echo "unexpected command"
	exit 1
fi

if [ "$arg" = 'start' ]; then
	if [ "$(pidof ccnud)" ]; then
		echo "ccnud shutdown..."
		killall ccnud
	fi

	if [ "$#" -ge '2' ]; then
		result=`~/projects/cs219_ccnumr/bin/ccnud $2`
	else
		result=`~/projects/cs219_ccnumr/bin/ccnud`
	fi

	echo "$result"

	if [ "$(pidof ccnumrd)" ]; then
		echo "ccnumrd shutdown..."
		killall ccnumrd
	fi

	sleep 1

	if [ "$#" -ge '3' ]; then
		result=`~/projects/cs219_ccnumr/bin/ccnumrd $3`
	else
		result=`~/projects/cs219_ccnumr/bin/ccnumrd`
	fi

	echo "$result"

elif [ "$arg" = 'stop' ]; then
	echo "stopping daemons..."
	killall ccnud
	killall ccnumrd
fi
